### PR TITLE
Address ISLANDORA-1643; Document how to handle discrepancies between …

### PR DESCRIPTION
**Pull request by ruebot**
…the code base and published ontology.

See: https://jira.duraspace.org/browse/ISLANDORA-1643

### CODE REVIEW

**Comment by manez** [comment]
Looks good to me as far as addressing the issue of conflicts and how to deal with them. Do we want/need a statement about which side of the conflict is presumed to win (allowing for corrections, as indicated by the JIRA wording you added).? This was the wording cited as an example at the Roadmap Meeting: "The English version of this specification is the only normative version. In case of conflicts, this ontology is the normative version. New changes can be submitted via JIRA tickets," following the example from WC3.

Or maybe that should be a different ticket, since this directly addresses 1643.

**Comment by mjordan** [comment]
Everything looks good to me.

**Comment by rosiel** [comment]
I'm sorry if things got a little convoluted when discussing conflicts. The potential for discrepancy that I saw (and which that verbiage from the Roadmap meeting was intended to clarify) was between the ontology as defined at http://github.com/Islandora/islandora_ontology vs. at http://islandora.ca/ontology/relsext/. Since they're meant to be identical versions of each other, but in reality the github one is likely to evolve faster than the exported version at islandora.ca, I wonder if we should either
a) consider the Github version the canonically published "newest version" at any point in time (and make sure that we update the versioning info as encoded in RDF any time we make changes), leaving the islandora.ca version as merely a convenience copy, which may or may not be out of date, **_or_**
b) consider islandora.ca to have the official, normative ontology, and consider the Github version to be the Working Draft (unpublished), and make the action of pushing any changes to islandora.ca the action of "publishing" a new version of the ontology.

The question of resolving conflicts between the ontology and existing/potential code in the codebase (as pointed out by @willtp87, and as described in JIRA ticket https://jira.duraspace.org/browse/ISLANDORA-1643), is a separate issue.

Regardless I think it'll be an important part of every release cycle to resolve any discrepancies between the islandora.ca ontology, the github version, and the code base.

**Comment by rosiel** [comment]
It makes sense from a technical perspective. It doesn't do anything for the philosophical problem of having two URLs that canonically define the same thing. But it seems like I'm the only one who thinks that's a problem, so I'll let the community proceed.

**Comment by rosiel** [comment]
@ruebot I see that my concern was misfounded and I'm sorry. Please proceed.

**Comment by willtp87** [comment]
As I mentioned in the Jira ticket I'm unsure on this and to be clearer here I defer judgment to consensus.

Thanks!

---

William Panting
_Developer_
_[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content_

**Comment by mjordan** [comment]
Merged as per 2016-04-01 roadmap dicussion.

**Pull request merged**
